### PR TITLE
Read schema file url

### PR DESCRIPTION
**Pull request by afwillia**
Addresses suggestion by @milen-sage to use schemas from a file or URL in addition to synapse's API.

Changes proposed in this pull request:

- Update get_template_keys_schema to accept a file/URL instead of only synapse ID

Please confirm you've done the following (if applicable):

- [ ] If adding or altering a configuration value, opened a PR in [dccmonitor](https://github.com/Sage-Bionetworks/dccmonitor) to update the same configuration value or verified that the configuration option is irrelevant in dccmonitor.
- [ ] Added tests for new functions or for new behavior in existing functions
- [ ] If adding a new exported function, added it to the reference section of `_pkgdown.yml`
- [ ] If adding a new configuration option, documented it in `vignettes/customizing_dccvalidator.Rmd`
- [x] If adding or changing functionality, documented it under "dccvalidator (development version)" in `NEWS.md`

### CODE REVIEW

**Review by avanlinden — APPROVED** [review]
Looks good!

**Comment by avanlinden** [comment]
Ah, although it looks like some of the unit tests for `get_file_schema` are failing in the actions. The R-CMD-check actions always fail on the ubuntu runners because they're out of date but they should still succeed on the macOS builds.

**Comment by afwillia** [comment]
I suspect I forgot to update some documentation after making those changes.
Will push a fix soon!

**Comment by afwillia** [comment]
dang, the ubuntu 16 vs 18 issue :face-palm:

**Comment by danlu1** [comment]
Just want to ask here. Which ubuntu version do we need to run the checks? 16 or 18?

**Comment by afwillia** [comment]
18.04 according to the [github documentation](
https://github.com/actions/virtual-environments#available-environments)

**Pull request merged**
