### PR TITLE
Validate data using JSON Schema

### LINKED ISSUE #72: Support validating from JSON Schema
Needed for PEC and eventually AMP-AD. Look into either using jsonvalidate (R) or reticulate + python package that @cw-dvr8 has been using.

### PR DESCRIPTION
**Pull request by karawoo**
Fixes #72. As discussed via email with @milen-sage and @kelshmo, I've added support for validating data with JSON Schema using the jsonvalidate R package (which may be replaced with a python library after #227 is merged, if needed).

Changes proposed in this pull request:

- Adds functions to check JSON data against a schema, as well as to check data in a data frame against a schema (by converting each row to JSON and iterating over them)

Please confirm you've done the following (if applicable):

- Added tests for new functions or for new behavior in existing functions: yes
- If adding a new exported function, added it to the reference section of `_pkgdown.yml`: yes
- If adding a new configuration option, documented it in `vignettes/customizing_dccvalidator.Rmd`: NA

---

Example usage is below. @kelshmo if you and/or @cw-dvr8 could test this out for PEC and, if there's anything that doesn't work properly, provide a [minimal reprex](https://reprex.tidyverse.org/) that would be great. Note this PR just adds the functions to the package, not to the shiny app yet.

``` r
schema <- '{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "x": {
      "type": "integer"
    },
    "y": {
      "type": "integer"
    }
  },
  "required": ["x", "y"]
}
'

## Check JSON data
json_valid <- '{
  "x": 3,
  "y": 5
}'

check_schema_json(json_valid, schema)
#> <check_pass: Data is valid against the schema>

## Check data frame data
dat <- data.frame(
  x = c(NA, 1, NA),
  y = c(NA, NA, "foo")
)

check_schema_df(dat, schema)
#> <error/check_fail>
#> Data is invalid against the schema
check_schema_df(dat, schema)$data
#> [[1]]
#>  should have required property 'x'
#>  should have required property 'y'
#> 
#> [[2]]
#>  should have required property 'y'
#> 
#> [[3]]
#>  should have required property 'x'
#> .y should be integer
```

<sup>Created on 2019-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by kelshmo** [comment]
- I tested the PsychENCODE [individual dereferenced schema - deref_individual_schema.json](https://github.com/cw-dvr8/JSON-validation-schemas/blob/master/dereferenced/deref_individual_schema.json) with a valid json object which returned  `class:   check_fail` due to the absence of the required properties. There were some "then" statements that could not be interpreted.
```
path <- "path/to/deref_individual_schema.json"

json_valid <- '{
  "species": "Human"
}'
> check_schema_json(json_valid, path)
 should have required property 'individualID'
 should have required property 'individualIdSource'
 should have required property 'reportedGender'
 should have required property 'postmortem'
 should have required property 'sexChromosome'
 should have required property 'race'
 should have required property 'raceDetail'
 should have required property 'genotypeInferredAncestry'
 should have required property 'IQ'
 should have required property 'BMI'
 should have required property 'primaryDiagnosis'
 should have required property 'primaryDiagnosisDetail'
 should have required property 'otherDiagnosis'
 should have required property 'familyHistory'
 should have required property 'ageOnset'
 should have required property 'neuropathDescription'
 should have required property 'dementia'
 should have required property 'otherMedicalDx'
 should match "then" schema
 should have required property 'PMICertain'
 should have required property 'PMI'
 should have required property 'pH'
 should have required property 'organWeight'
 should have required property 'organRIN'
 should have required property 'yearAutopsy'
 should match "then" schema

```

- Currently, using `jsonvalidate 1.1.0` that may explain the `$id` failure.

**Comment by cw-dvr8** [comment]
As a test, I ran this schema through the [validate_using_schema.py](https://github.com/Sage-Bionetworks/dccjsonvalidation/blob/master/dccjsonvalidation/validate_using_schema.py) program using the individual_human_pass.csv file, and it did generate a few errors but they were valid based on the current schema properties and the contents of the .csv file.  The Python program uses a JSON Schema Draft 7 validator.

**Comment by kelshmo** [comment]
Reinstalling the macOS toolchain and updating to `jsonvalidate 1.2.2` resolved the `$id` error and discrepancies between the package version and lock file.

**Comment by karawoo** [comment]
@kelshmo do you want me to sort out the if/then issue before we merge this PR, or is it ok to merge now?

**Comment by kelshmo** [comment]
@karawoo  We can merge! I will open an issue to track the debugging of the "then" statements.

**Pull request merged**
