### PR TITLE
Reorganize documentation with pkgdown + vignettes

### PR DESCRIPTION
**Pull request by karawoo**
@kelshmo this has a draft vignette for #95 and reorganizes the documentation to make the README more concise. It adds a [pkgdown](https://pkgdown.r-lib.org/) site which you can see locally with `pkgdown::build_site()`. @Aryllen and I discussed pros/cons of pkgdown -- the main downside I see is the potential to confuse data contributors, who really only need to view one vignette, with the rest of the content on the site. I tried it out just to see how it looks and think on it some more. Feel free to take the branch and make any updates you want, or go in a new direction entirely.

I wrote the vignette with language specific to AMP-AD, but we could remove that if we don't want to maintain separate sets of instructions. However the screenshots etc. will have the wrong URL for one or the other consortium, which might be confusing.

### CODE REVIEW

**Comment by kelshmo** [comment]
@karawoo does `pkgdown` need to be specified in the `renv.lock` file to be able to run `pkgdown::build_site()`?

**Comment by karawoo** [comment]
pkgdown needs to be installed, though not necessarily through the lockfile. By default renv only stores build- and deploy-time dependencies, not packages for interactive development (this is why lintr, styler, etc. are not included): https://rstudio.github.io/renv/articles/faq.html#how-should-i-handle-development-dependencies. I'm open to including these, but is has the potential to add a lot of extra stuff that not everyone who is cloning the project may need.

**Comment by kelshmo** [comment]
Ok - I'm fine with not including it since it is only required for development. 

> the main downside I see is the potential to confuse data contributors

The availability of this documentation is important for many different end-users. What do you think about, for our data contributors, linking directly from the app to to the articles page - e.g. "Using the dccvalidator app in AMP-AD"?

**Comment by karawoo** [comment]
Agreed we'd want to link them directly to the page of interest. They still might see other stuff that's irrelevant to them in the header bar. But I think that is probably ok, and preferable compared to emailing them a document that may become out of date and that they might lose.

**Comment by kelshmo** [comment]
I have a draft vignette for PEC like your [AMP-AD draft](vignettes/using-the-dccvalidator-app-amp-ad.Rmd). What is the best way to contribute this doc? Open a new PR with only the additional .Rmd document? I would love to get some feedback even if the PR remains a draft for the moment. I can host it on Synapse for the face to face tomorrow so there is not pressure to get this online.

**Comment by karawoo** [comment]
Great! Do you want to open a new PR against this branch?

**Comment by karawoo** [comment]
@kelshmo I added the images and re-rendered everything, will you take a look and let me know if you think we're ready to merge?

**Comment by karawoo** [comment]
ugghhh I thought I solved the images issue but apparently not

**Comment by karawoo** [comment]
> Images look great! I see 4 rendering on the AMP-AD vignettes with nice drop shadow. Ready to merge - I will add screenshots for PEC in another PR.

The problem was they were rendering in the pkgdown site, but not when Travis tried to build the vignettes (hence the failing build). I've pushed a change that I hope will fix it 🤞

**Pull request merged**
